apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}-configmap
data:
  {{- range $key, $val := .Values.configmap.application.envs }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
