---
name: Release Charts
run-name: Workflow ${{ github.workflow }} Release {{ github.event.release.tag_name }} ${{ github.event_name }}

on:
  release:
    types: [released]

jobs:

  release:
    name: Release API Definition
    runs-on: ubuntu-latest    
    steps:
      - name: 🔨 Set up environment - TBD
        run: echo "🔨 Set up environment - TBD"
      - name: 📂 Checkout Repository
        run: echo "📂 Checkout Repository"
      - name: 🚀 Publish API Version
        run: echo "🚀 Publish API Version on Gluon"

  publish:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"